#插件优先级
priority: 55

#是否自动签到
AutoSign: false
#自动签到定时任务(更改需要重启)
signTime: 0 4 0 * * ?
#签到游戏
game:
 - gs
 - sr
 - zzz
 - bh3
#签到重试次数
retry: 2
#社区是否自动签到
AutobbsSign: true
#自动签到定时任务(更改需要重启)
bbsSignTime: 5 4 0 * * ?
#签到重试次数
bbsRetry: 3

#是否开启体力推送
NoteTask: true
#体力推送查询间隔，默认30分钟
TaskTime: 0 0/30 * * * ?
#体力推送CD(小时)
sendCD: 1
#默认推送阈值
gs_Resin: 160
sr_Resin: 200
zzz_Resin: 200
#合并转发
forward: 2
#推送文案
TaskMsg: 你的体力快满了哦~

#失效qq每行显示个数
invalid: 2

#本体过码重试次数
retrytime: 2
#显示所有请求日志
isLog: false
#显示所有返回日志
resLog: false

#是否自动删除ck
Autodelck: false
#是否自动删除sk
Autodelsk: false